### ISSUE TITLE
No owner_id(s) keyword-arguments on Bot or AutoShardedBot

### ISSUE THREAD

**Issue by SeparateRecords** [bryanforbes/discord.py-stubs#30]
Thanks for your work on this! It's made the experience of using d.py so much better.

Ran into something my bot uses -- `commands.Bot` allows you to specify `owner_id` or `owner_ids` in the constructor, which the stubs don't have.

```py
from discord.ext import commands

bot = commands.Bot(command_prefix=".", owner_id=123456789123456789)
#                                      ~~~~~~~~
#
# owner_id should be Optional[int],
# owner_ids should be Optional[Collection[int]]
```

Also might be worth changing `Bot.owner_ids` to `Optional[Collection[int]]` ([a `Set[int]` is recommended, not required](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.owner_ids))

**Comment by bryanforbes** [comment]
This has been fixed and released in 1.5.1.1
