### ISSUE TITLE
Guild.me is typed as an optional, while it is not in the doc

### ISSUE THREAD

**Issue by Shaac** [bryanforbes/discord.py-stubs#51]
Hello,
Thanks for this project!

I noticed that `Guild.me` was typed as a `Optional[Member]`, but it is not how it is documented in [the discord.py documentation](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.voice_channels).

https://github.com/bryanforbes/discord.py-stubs/blob/eb3e8afe9dd171f4da37df712a9a96a6a17e1643/discord-stubs/guild.pyi#L101

Unless it is an error in discord.py documentation, the Optional should probably be dropped here.

Thanks!

**Comment by bryanforbes** [comment]
I based the typing of `Guild.me` on the code, which calls `Guild.get_member()` and that returns `Optional[Member]`. I'll do some digging and see if that can be changed.

**Comment by bryanforbes** [comment]
I verified with someone in the Discord server and have updated the typing. I'll make a new release later today.

**Comment by bryanforbes** [comment]
Version 1.6.0.1 (which includes this fix) has been released on pypi
