### ISSUE TITLE
view_channel permission alias is not supported

### ISSUE THREAD

**Issue by Shaac** [bryanforbes/discord.py-stubs#52]
Hello,

Should I write `chan.set_permissions(role, view_channel=True, connect=True)`, which works perfectly when executing, mypy is not happy at all : `error: No overload variant of "set_permissions" of "GuildChannel" matches argument types "Role", "bool", "bool"`.

If I replace `view_channel` by its alias `read_messages`, mypy works fine.

While the workaround is perfectly acceptable, it would be nice if discord.py-stubs supported the alias.

Here is a link to the discord.py documentation for reference: https://discordpy.readthedocs.io/en/latest/api.html#discord.Permissions.view_channel

**Comment by bryanforbes** [comment]
Thanks for the report. I've updated the `Permissions` and `GuildChannel.set_permissions()` typing and will make a new release later today.

**Comment by bryanforbes** [comment]
Version 1.6.0.1 (which includes this fix) has been released on pypi
