### ISSUE TITLE
Incorrect type stub for fetch_members

### ISSUE THREAD

**Issue by dob9601** [bryanforbes/discord.py-stubs#63]
Method is marked as async [here](https://github.com/bryanforbes/discord.py-stubs/blob/ac6aa125a382b98c9f16b85f781e3ffca79b3100/discord-stubs/guild.pyi#L251-L256), when in fact it is a synchronous method within discord.py. See [here](https://github.com/Rapptz/discord.py/blob/0c3be9713d74c4b9fb90b0b9fee8f4680060c68e/discord/guild.py#L1263)

**Comment by dob9601** [comment]
Nope, for now I've just told my linter to ignore the type

**Comment by bryanforbes** [comment]
I went ahead and created a new release for the `1.6` stub files
