### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by Markusnarillious** [bryanforbes/discord.py-stubs#81]
I still didnt get paid from my last work

**Comment by ZanderBrown** [comment]
Feels like spam to me

**Comment by Markusnarillious** [comment]
Yeah it is spam...im looking around repositorys

**Comment by ZanderBrown** [comment]
Huh

**Comment by Markusnarillious** [comment]
I just like the number

**Comment by Markusnarillious** [comment]
Yeah i have a dictonary in all python code.
